#! /bin/bash

INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=AppServer" "Name=instance-state-name,Values=running" --query 'Reservations[*].Instances[*].InstanceId' --output text)
aws ssm start-session --target $INSTANCE_ID