# Generated by Django 5.2 on 2025-04-20 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("endpoint", models.CharField(max_length=255)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Attraction",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("entity_type", models.CharField(max_length=50)),
                ("external_id", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Park",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("entity_type", models.CharField(max_length=50)),
                ("timezone", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="AttractionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(max_length=50)),
                ("standby_wait_time", models.IntegerField(blank=True, null=True)),
                ("single_rider_wait_time", models.IntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="theme_park_data.attraction",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="OperatingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "attraction_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_hours",
                        to="theme_park_data.attractionstatus",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Operating hours",
                "ordering": ["start_time"],
            },
        ),
        migrations.AddField(
            model_name="attraction",
            name="park",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attractions",
                to="theme_park_data.park",
            ),
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("entity_type", models.CharField(max_length=50)),
                ("external_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="theme_park_data.park",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShowStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(max_length=50)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="theme_park_data.show",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Showtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "show_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showtimes",
                        to="theme_park_data.showstatus",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="attractionstatus",
            index=models.Index(
                fields=["attraction", "timestamp"],
                name="theme_park__attract_1bd9a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="showstatus",
            index=models.Index(
                fields=["show", "timestamp"], name="theme_park__show_id_965753_idx"
            ),
        ),
    ]
